---
- name: 🚀 Deploy via Pure SSM (Agent Mode)
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # This automatically grabs the Instance IDs from your inventory
    target_instances: "{{ groups['all'] }}"
    
  tasks:
    - name: 📡 Send Docker Instruction to AWS SSM Agents
      amazon.aws.ssm_send_command:  # <--- Changed from community.aws to amazon.aws
        instance_ids: "{{ target_instances }}"
        region: us-east-1
        document_name: "AWS-RunShellScript"
        parameters:
          commands:
            - "sudo docker pull hashicorp/http-echo"
            - "sudo docker rm -f showcase-app || true"
            - "sudo docker run -d --name showcase-app -p 8080:5678 hashicorp/http-echo -text='<h1>🚀 DevOps Success!</h1><p>Managed via AWX Pure SSM</p>'"
      register: ssm_result

    - name: ✅ Command Sent Successfully
      debug:
        msg: "Instruction sent to {{ target_instances | length }} servers. Request ID: {{ ssm_result.command_id }}"
