---
- name: 🚀 Deploy via Raw Python (The "Diamond Bullet" Fix)
  hosts: localhost
  connection: local
  gather_facts: yes
  become: false
  vars:
    instance_list: "{{ groups['all'] | join(' ') }}"

  tasks:
    - name: 📝 Create Python Deployment Script
      copy:
        dest: "/tmp/deploy_ssm.py"
        mode: '0755'
        content: |
          import boto3
          import os
          import sys
          
          # 1. Parse Inputs
          try:
              instance_ids = sys.argv[1].split()
              if not instance_ids:
                  print("❌ No instance IDs found!")
                  sys.exit(1)
          except IndexError:
               print("❌ No instance IDs passed!")
               sys.exit(1)

          print(f"🚀 Target Instances: {instance_ids}")

          # 2. Connect to AWS SSM (Using Env Vars)
          try:
              # Boto3 will automatically pick up AWS_ACCESS_KEY_ID etc from the environment
              ssm = boto3.client('ssm', region_name='us-east-1')
          except Exception as e:
              print(f"❌ AWS Connection Failed: {str(e)}")
              sys.exit(1)

          # 3. The Docker Command
          commands = [
              "sudo docker pull hashicorp/http-echo",
              "sudo docker rm -f showcase-app || true",
              "sudo docker run -d --name showcase-app -p 8080:5678 hashicorp/http-echo -text='<h1>🚀 DevOps Success!</h1><p>Managed via AWX & Boto3</p>'"
          ]

          # 4. Send the Command
          try:
              print("📡 Sending command to fleet...")
              response = ssm.send_command(
                  InstanceIds=instance_ids,
                  DocumentName="AWS-RunShellScript",
                  Parameters={'commands': commands}
              )
              cmd_id = response['Command']['CommandId']
              print(f"✅ Success! Command ID: {cmd_id}")
          except Exception as e:
              print(f"❌ Failed to send command: {str(e)}")
              sys.exit(1)

    - name: 📡 Execute Deployment Script
      command: "{{ ansible_playbook_python }} /tmp/deploy_ssm.py '{{ instance_list }}'"
      # 👇 THIS IS THE MAGIC PART 👇
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') | default(lookup('env', 'AWS_ACCESS_KEY'), true) }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') | default(lookup('env', 'AWS_SECRET_KEY'), true) }}"
        AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default('') }}"
        AWS_REGION: "us-east-1"
      register: deploy_output

    - name: 📄 Show Result
      debug:
        msg: "{{ deploy_output.stdout_lines }}"
