---
- name: 🚀 Standard CLI Test (Bypassing Connection Plugins)
  hosts: all
  gather_facts: no
  # We REMOVE connection: local from here
  
  tasks:
    - name: 📡 Run Docker via AWS CLI (Delegated)
      shell: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids "{{ inventory_hostname }}" \
          --region us-east-1 \
          --parameters 'commands=["sudo docker pull python:3.11-alpine", "sudo docker run -d --name alpine-python python:3.11-alpine sleep 3600"]'
      # This forces the task to run on the AWX pod's shell
      delegate_to: localhost
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default('', true) }}"
      register: ssm_out

    - name: ✅ Verify Command Sent
      debug:
        msg: "Success! Check your EC2 for the alpine-python container."
