---
- name: 🚀 Trigger Enterprise GitOps Deployment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: 📡 Wake up SSM Association
      amazon.aws.aws_ssm_association_execution:
        association_id: "YOUR_ASSOCIATION_ID" # Get this from the State Manager console
        region: us-east-1
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
