---
- name: 🚀 Trigger Enterprise GitOps Deployment (Final)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: 📡 Wake up SSM Association
      shell: |
        {{ ansible_playbook_python }} -c "
        import boto3
        client = boto3.client('ssm', region_name='us-east-1')
        client.start_associations_once(
            AssociationIds=['a92127cf-65ae-46be-a8d3-c503b3c20214']
        )
        print('SUCCESS: Trigger sent to AWS.')
        "
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default('', true) }}"
