---
- name: 🚀 Trigger Enterprise GitOps Deployment (Safe Mode)
  hosts: localhost
  gather_facts: no
  become: false  # Added to prevent sudo issues on the AWX pod
  tasks:
    - name: 📡 Wake up SSM Association via Internal Boto3
      shell: |
        {{ ansible_playbook_python }} -c "
        import boto3, os
        client = boto3.client('ssm', region_name='us-east-1')
        try:
            response = client.start_associations_once(
                InstanceIds=[], 
                AssociationIds=['a92127cf-65ae-46be-a8d3-c503b3c20214']
            )
            print(f'SUCCESS: {response[\"ResponseMetadata\"][\"HTTPStatusCode\"]}')
        except Exception as e:
            print(f'FAILED: {str(e)}')
            exit(1)
        "
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default('', true) }}"
      register: trigger_output

    - name: ✅ Show Result
      debug:
        var: trigger_output.stdout
